### ISSUE TITLE
Include LICENSE.txt into PyPi's release archive

### ISSUE THREAD

**Issue by yegorich** [bb4242/sdnotify#1]
Could you add LICENSE.txt to PyPi's release archive?

Thanks

**Comment by bb4242** [comment]
Sure, I'm happy to help with this, but can you please provide a bit more detail on what exactly you're asking for?  The pypi package is already tagged with a `License :: OSI Approved :: MIT License` classifier, and `LICENSE.txt` is present in the package [tarball](https://github.com/bb4242/sdnotify/tarball/v0.3.0).  I also just added `MIT License` to pypi's `License` metadata for the package, although I'm not sure if that's recommended when a license classifier is also being used.  See [here](https://pypi.python.org/pypi/sdnotify/0.3.0).  Does that satisfy your requirements?

**Comment by yegorich** [comment]
Some background info: I'm trying to integrate sdnotify into [Buildroot](https://buildroot.org/). If possible we always try to download packages from PyPi. Most packages have license file in the release tarball, that is uploaded to PyPi. That's why I was asking you to put it there. Via `make legal-info` command license files will extracted and put into extra folder. See BR's [documentation](http://nightly.buildroot.org/manual.html#legal-info) for details.

**Comment by bb4242** [comment]
Ah, I see.  OK, I just pushed a new version of the package (`0.3.1`) to pypi, with the changes in cc7da0c83a2.  Can you try this new version and see if it meets your needs?  If it doesn't, can you point me to an existing package that correctly includes the license as you need it so I can see how they do it?  This is my first time publishing on pypi, so I'm learning some of this as I go. :)

**Comment by yegorich** [comment]
0.3.1 is working as expected. Thanks.

**Comment by bb4242** [comment]
Great, glad it's working!
